DemoMVCApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoMVCApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

      
    }
}

DemoMVCApp/Controllers/ProductController.cs
using DAL;
using BLL;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UTIL;


namespace DemoMVCApp.Controllers
{
    public class ProductController : Controller
    {

        Logger logger = Logger.GetInstance();

        // GET: Proizvodi
        public ActionResult Index()
        {
            try
            {
                ProductsService products = new ProductsService();
                List<Product> prods = products.ListOfProducts();
                return View(prods);
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
            }
            
            return View("~/Views/Shared/Error.cshtml");
        }

        public ActionResult ListOfProducts()
        {
            try
            {
                ProductsService products = new ProductsService();
                List<Product> prods = products.ListOfProducts();
                return View(prods);
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
            }

            return View("~/Views/Shared/Error.cshtml");
        }


        public ActionResult NewProduct()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewProduct(Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (BaseEntities context = new BaseEntities())
                    {
                        context.Products.Add(product);
                        context.SaveChanges();
                        logger.Info("Successfully added record in the database regarding Products");
                        return RedirectToAction("Index", "Product");
                    }
                }
            }
            catch (Exception e)
            {
                
                logger.Error(e.Message);
                ModelState.AddModelError("Product", e.Message);
                
            }

            return View("~/Views/Shared/Error.cshtml");
        }
        
        // GET Products/Edit/1
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return HttpNotFound();
            }
            try
            {
                Product product = new Product();
                if (ModelState.IsValid)
                {

                    using (BaseEntities context = new BaseEntities())
                    {
                        product = context.Products.SingleOrDefault(e => e.ProductId == id);
                        if (product == null || id == 0)
                        {
                            return HttpNotFound();
                        }
                        logger.Info("Product found and can be edited");   
                    }
                }

                return View(product);
            }
            catch (ArgumentException e)
            {
                logger.Error(e.Message);
                ModelState.AddModelError("Product",e.Message);
               
            }

            return View("~/Views/Shared/Error.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveChanges([Bind(Include = "ProductId, Name, Description, Category, Brand, Supplier, Price")]Product products)
        {

            try
            {
                if (ModelState.IsValid)
                {

                    using (BaseEntities context = new BaseEntities())
                    {
                        context.Entry(products).State = EntityState.Modified;
                        context.SaveChanges();
                        logger.Info("Successfully edited record in the database regarding Products");
                        return RedirectToAction("Index", "Product");

                    }
                }
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                ModelState.AddModelError("Product", e.Message);
                
            }

            return View("~/Views/Shared/Error.cshtml");
        }

    }
}

DemoMVCApp/Controllers/ProductJSONController.cs
using BLL;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UTIL;

namespace DemoMVCApp.Controllers
{
    public class ProductJSONController : Controller
    {
        Logger logger = Logger.GetInstance();

        // GET: ProductJSON
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListOfProductsJSON()
        {
            try
            {
                ProductsService products = new ProductsService();
                List<Product> prods = products.ListOfProductsJSON();
                return View(prods);
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
            }

            return View("~/Views/Shared/Error.cshtml");
        }
    }
}

DemoMVCApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h1>App demo Index</h1>

DemoMVCApp/Views/Product/Edit.cshtml
@model DAL.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("SaveChanges","Product",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Products</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control" , @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.ProductId, "Field is a read only", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control", required = "required"} })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Supplier, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Supplier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DemoMVCApp/Views/Product/Index.cshtml
@model IEnumerable<DAL.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Html.ActionLink("List of products from base", "ListOfProducts", null, new { @class = "btn btn-lg btn-primary" })</h2><br>
<div class="center-block dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Edit Products
        <span class="caret">
        </span>
    </button>
    <ul class="dropdown-menu" role="menu">
    @foreach (var item in Model)
    {
        <li>@Html.ActionLink("EDIT product " + item.Name, "Edit", new {id = item.ProductId})</li>
    }
    </ul>
</div>

DemoMVCApp/Views/Product/ListOfProducts.cshtml
@model IEnumerable<DAL.Product>

@{
    ViewBag.Title = "List of Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (Model != null)
{
    <div class="container" style="width: 50%; margin-top: 2%">
        
        <table class="table table-bordered table-striped">
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Category</th>
                <th>Brand</th>
                <th>Supplier</th>
                <th>Price</th>
            </tr>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Description</td>
                        <td>@item.Category</td>
                        <td>@item.Brand</td>
                        <td>@item.Supplier</td>
                        <td>@item.Price</td>
                   </tr>
                }
    
            </tbody>
        </table>
    </div>
}

DemoMVCApp/Views/Product/NewProduct.cshtml
@model DAL.Product

@{
    ViewBag.Title = "New Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Product</h2>

@using (Html.BeginForm("NewProduct", "Product", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(l => l.Price)
        @Html.TextBoxFor(l => l.Price, new {@class = "form-control", required = "required" })
    </div>

    <div class="form-group">
        @Html.LabelFor(l => l.Supplier)
        @Html.TextBoxFor(l => l.Supplier, new {@class = "form-control", required = "required" })
    </div>

    <div class="form-group">
        @Html.LabelFor(l => l.Category)
        @Html.TextBoxFor(l => l.Category, new {@class = "form-control", required = "required" })
    </div>

    <div class="form-group">
        @Html.LabelFor(l => l.Name)
        @Html.TextBoxFor(l => l.Name, new {@class = "form-control", required = "required" } )
    </div>

    <div class="form-group">
        @Html.LabelFor(l => l.Description)
        @Html.TextBoxFor(l => l.Description, new {@class = "form-control", required = "required" })
    </div>

    <div class="form-group">
        @Html.LabelFor(l => l.Brand)
        @Html.TextBoxFor(l => l.Brand, new {@class = "form-control", required = "required" })
    </div>

    <button type="submit" class="btn btn-danger">Add new product</button>


}

DemoMVCApp/Views/Product/SaveChanges.cshtml
@model DAL.Product

@{
    ViewBag.Title = "SaveChanges";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editing failed</h2>

DemoMVCApp/Views/ProductJSON/Index.cshtml
@model IEnumerable<DAL.Product>

@{
    ViewBag.Title = "List of products from JSON-a";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>@Html.ActionLink("List of products from JSON file", "ListOfProductsJSON",null, new { @class = "btn btn-lg btn-primary " })</h2>

DemoMVCApp/Views/ProductJSON/ListOfProductsJSON.cshtml
@model IEnumerable<DAL.Product>

@{
    ViewBag.Title = "List of products from JSON-a";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (Model != null)
{
    <div class="container" style="width: 50%; margin-top: 2%">
        
        <table class="table table-bordered table-striped">
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Category</th>
                <th>Brand</th>
                <th>Supplier</th>
                <th>Price</th>
            </tr>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>@item.Category</td>
                    <td>@item.Brand</td>
                    <td>@item.Supplier</td>
                    <td>@item.Price</td>
                </tr>
            }
    
            </tbody>
        </table>
    </div>
}

DemoMVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle btn-group" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                @Html.ActionLink("Index page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Products JSON", "Index", "ProductJSON")</li>
                    <li>@Html.ActionLink("Adding a new product", "NewProduct", "Product")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>